name: Validate
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Checkout the project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run 'terraform init'
        run: terraform init

      - name: Run 'terraform fmt'
        run: terraform fmt -check

      - name: Run 'terraform validate'
        run: terraform validate

      - name: Create required parameters
        run: |
          touch terraform.tfvars
          echo fpjs_agent_download_path = "agent" >> terraform.tfvars
          echo fpjs_get_result_path = "result" >> terraform.tfvars
          echo fpjs_shared_secret = "secret" >> terraform.tfvars

      - name: Run 'terraform plan'
        run: terraform plan -input=false
